iucn = {
    
    ['iucn2.3'] = {
        ['kode'] = '&nbsp;([[IUCN|IUCN 2.3]])',
        ['EX'] = '[[Vaizdas:Status iucn2.3 EX.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Išnykę|Išnykę]]',
        ['ex'] = '[[Vaizdas:Status iucn2.3 EX.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Išnykę|Išnykę]]',
        ['EW'] = '[[Vaizdas:Status iucn2.3 EW.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Išnykę laisvėje|Išnykę laisvėje]]',
        ['ew'] = '[[Vaizdas:Status iucn2.3 EW.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Išnykę laisvėje|Išnykę laisvėje]]',
        ['CR'] = '[[Vaizdas:Status iucn2.3 CR.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]]',
        ['cr'] = '[[Vaizdas:Status iucn2.3 CR.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]]',
        ['EN'] = '[[Vaizdas:Status iucn2.3 EN.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Nykstantys|Nykstantys]]',
        ['en'] = '[[Vaizdas:Status iucn2.3 EN.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Nykstantys|Nykstantys]]',
        ['VU'] = '[[Vaizdas:Status iucn2.3 VU.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Pažeidžiami|Pažeidžiami]]',
        ['vu'] = '[[Vaizdas:Status iucn2.3 VU.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Pažeidžiami|Pažeidžiami]]',
        ['LR'] = '[[Vaizdas:Status iucn2.3 blank.svg|link = |alt = ]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['lr'] = '[[Vaizdas:Status iucn2.3 blank.svg|link = |alt = ]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['CD'] = '[[Vaizdas:Status iucn2.3 CD.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Būtina apsauga|Būtina apsauga]]',
        ['cd'] = '[[Vaizdas:Status iucn2.3 CD.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Būtina apsauga|Būtina apsauga]]',
        ['LR/CD'] = '[[Vaizdas:Status iucn2.3 CD.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Būtina apsauga|Būtina apsauga]]',
        ['lr/CD'] = '[[Vaizdas:Status iucn2.3 CD.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Būtina apsauga|Būtina apsauga]]',
        ['LR/cd'] = '[[Vaizdas:Status iucn2.3 CD.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Būtina apsauga|Būtina apsauga]]',
        ['lr/cd'] = '[[Vaizdas:Status iucn2.3 CD.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Būtina apsauga|Būtina apsauga]]',
        ['NT'] = '[[Vaizdas:Status iucn2.3 NT.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['nt'] = '[[Vaizdas:Status iucn2.3 NT.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['LR/NT'] = '[[Vaizdas:Status iucn2.3 NT.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['lr/NT'] = '[[Vaizdas:Status iucn2.3 NT.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['LR/nt'] = '[[Vaizdas:Status iucn2.3 NT.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['lr/nt'] = '[[Vaizdas:Status iucn2.3 NT.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['LC'] = '[[Vaizdas:Status iucn2.3 LC.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['lc'] = '[[Vaizdas:Status iucn2.3 LC.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['LR/LC'] = '[[Vaizdas:Status iucn2.3 LC.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['lr/LC'] = '[[Vaizdas:Status iucn2.3 LC.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['LR/lc'] = '[[Vaizdas:Status iucn2.3 LC.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['lr/lc'] = '[[Vaizdas:Status iucn2.3 LC.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['DD'] = '[[Vaizdas:Status iucn2.3 blank.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė|Trūksta duomenų]]',
        ['dd'] = '[[Vaizdas:Status iucn2.3 blank.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė|Trūksta duomenų]]',
        ['NE'] = "''Nenustatyta''",
        ['ne'] = "''Nenustatyta''",
        ['NR'] = "''Nežinoma''",
        ['nr'] = "''Nežinoma''",
        ['PE'] = "[[Vaizdas:Status iucn2.3 CR.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę",
        ['pe'] = "[[Vaizdas:Status iucn2.3 CR.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę",
        ['PEW'] = "[[Vaizdas:Status iucn2.3 CR.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę laisvėje",
        ['pew'] = "[[Vaizdas:Status iucn2.3 CR.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę laisvėje",
        ['#default'] = "'''''Blogas statusas'''''"
    },
    ['IUCN2.3'] = {
        ['kode'] = '&nbsp;([[IUCN|IUCN 2.3]])',
        ['EX'] = '[[Vaizdas:Status iucn2.3 EX.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Išnykę|Išnykę]]',
        ['ex'] = '[[Vaizdas:Status iucn2.3 EX.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Išnykę|Išnykę]]',
        ['EW'] = '[[Vaizdas:Status iucn2.3 EW.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Išnykę laisvėje|Išnykę laisvėje]]',
        ['ew'] = '[[Vaizdas:Status iucn2.3 EW.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Išnykę laisvėje|Išnykę laisvėje]]',
        ['CR'] = '[[Vaizdas:Status iucn2.3 CR.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]]',
        ['cr'] = '[[Vaizdas:Status iucn2.3 CR.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]]',
        ['EN'] = '[[Vaizdas:Status iucn2.3 EN.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Nykstantys|Nykstantys]]',
        ['en'] = '[[Vaizdas:Status iucn2.3 EN.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Nykstantys|Nykstantys]]',
        ['VU'] = '[[Vaizdas:Status iucn2.3 VU.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Pažeidžiami|Pažeidžiami]]',
        ['vu'] = '[[Vaizdas:Status iucn2.3 VU.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Pažeidžiami|Pažeidžiami]]',
        ['LR'] = '[[Vaizdas:Status iucn2.3 blank.svg|link = |alt = ]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['lr'] = '[[Vaizdas:Status iucn2.3 blank.svg|link = |alt = ]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['CD'] = '[[Vaizdas:Status iucn2.3 CD.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Būtina apsauga|Būtina apsauga]]',
        ['cd'] = '[[Vaizdas:Status iucn2.3 CD.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Būtina apsauga|Būtina apsauga]]',
        ['LR/CD'] = '[[Vaizdas:Status iucn2.3 CD.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Būtina apsauga|Būtina apsauga]]',
        ['lr/CD'] = '[[Vaizdas:Status iucn2.3 CD.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Būtina apsauga|Būtina apsauga]]',
        ['LR/cd'] = '[[Vaizdas:Status iucn2.3 CD.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Būtina apsauga|Būtina apsauga]]',
        ['lr/cd'] = '[[Vaizdas:Status iucn2.3 CD.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Būtina apsauga|Būtina apsauga]]',
        ['NT'] = '[[Vaizdas:Status iucn2.3 NT.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['nt'] = '[[Vaizdas:Status iucn2.3 NT.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['LR/NT'] = '[[Vaizdas:Status iucn2.3 NT.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['lr/NT'] = '[[Vaizdas:Status iucn2.3 NT.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['LR/nt'] = '[[Vaizdas:Status iucn2.3 NT.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['lr/nt'] = '[[Vaizdas:Status iucn2.3 NT.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['LC'] = '[[Vaizdas:Status iucn2.3 LC.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['lc'] = '[[Vaizdas:Status iucn2.3 LC.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['LR/LC'] = '[[Vaizdas:Status iucn2.3 LC.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['lr/LC'] = '[[Vaizdas:Status iucn2.3 LC.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['LR/lc'] = '[[Vaizdas:Status iucn2.3 LC.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['lr/lc'] = '[[Vaizdas:Status iucn2.3 LC.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['DD'] = '[[Vaizdas:Status iucn2.3 blank.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė|Trūksta duomenų]]',
        ['dd'] = '[[Vaizdas:Status iucn2.3 blank.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė|Trūksta duomenų]]',
        ['NE'] = "''Nenustatyta''",
        ['ne'] = "''Nenustatyta''",
        ['NR'] = "''Nežinoma''",
        ['nr'] = "''Nežinoma''",
        ['PE'] = "[[Vaizdas:Status iucn2.3 CR.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę",
        ['pe'] = "[[Vaizdas:Status iucn2.3 CR.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę",
        ['PEW'] = "[[Vaizdas:Status iucn2.3 CR.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę laisvėje",
        ['pew'] = "[[Vaizdas:Status iucn2.3 CR.svg|frameless|link=|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę laisvėje",
        ['#default'] = "'''''Blogas statusas'''''"
    },

    ['iucn'] = {
        ['kode'] = '&nbsp;([[IUCN|IUCN 3.1]])',
        ['EX'] = '[[Vaizdas:Status iucn3.1 EX lt.svg|frameless|link=Apsaugos būklė#Išnykę|alt=]]<br />[[Apsaugos būklė#Išnykę|Išnykę]]',
        ['ex'] = '[[Vaizdas:Status iucn3.1 EX lt.svg|frameless|link=Apsaugos būklė#Išnykę|alt=]]<br />[[Apsaugos būklė#Išnykę|Išnykę]]',
        ['EW'] = '[[Vaizdas:Status iucn3.1 EW lt.svg|frameless|link=Apsaugos būklė#Išnykę laisvėje|alt=]]<br />[[Apsaugos būklė#Išnykę laisvėje|Išnykę laisvėje]]',
        ['ew'] = '[[Vaizdas:Status iucn3.1 EW lt.svg|frameless|link=Apsaugos būklė#Išnykę laisvėje|alt=]]<br />[[Apsaugos būklė#Išnykę laisvėje|Išnykę laisvėje]]',
        ['CR'] = '[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]]',
        ['cr'] = '[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]]',
        ['EN'] = '[[Vaizdas:Status iucn3.1 EN lt.svg|frameless|link=Apsaugos būklė#Nykstantys|alt=]]<br />[[Apsaugos būklė#Nykstantys|Nykstantys]]',
        ['en'] = '[[Vaizdas:Status iucn3.1 EN lt.svg|frameless|link=Apsaugos būklė#Nykstantys|alt=]]<br />[[Apsaugos būklė#Nykstantys|Nykstantys]]',
        ['VU'] = '[[Vaizdas:Status iucn3.1 VU lt.svg|frameless|link=Apsaugos būklė#Pažeidžiami|alt=]]<br />[[Apsaugos būklė#Pažeidžiami|Pažeidžiami]]',
        ['vu'] = '[[Vaizdas:Status iucn3.1 VU lt.svg|frameless|link=Apsaugos būklė#Pažeidžiami|alt=]]<br />[[Apsaugos būklė#Pažeidžiami|Pažeidžiami]]',
        ['NT'] = '[[Vaizdas:Status iucn3.1 NT lt.svg|frameless|link=Apsaugos būklė#Beveik nykstantys|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['nt'] = '[[Vaizdas:Status iucn3.1 NT lt.svg|frameless|link=Apsaugos būklė#Beveik nykstantys|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['LC'] = '[[Vaizdas:Status iucn3.1 LC lt.svg|frameless|link=Apsaugos būklė#Nekeliantys susirūpinimo|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['lc'] = '[[Vaizdas:Status iucn3.1 LC lt.svg|frameless|link=Apsaugos būklė#Nekeliantys susirūpinimo|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['DD'] = '[[Vaizdas:Status iucn3.1 lt.svg|frameless|link=|alt=]]<br/>[[Apsaugos būklė|Trūksta duomenų]]',
        ['dd'] = '[[Vaizdas:Status iucn3.1 lt.svg|frameless|link=|alt=]]<br/>[[Apsaugos būklė|Trūksta duomenų]]',
        ['NE'] = "''Nenustatyta''",
        ['ne'] = "''Nenustatyta''",
        ['NR'] = "''Nežinoma''",
        ['nr'] = "''Nežinoma''",
        ['PE'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę",
        ['pe'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę",
        ['PEW'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę laisvėje",
        ['pew'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę laisvėje",
        ['#default'] = "'''''Blogas statusas'''''"
    },
    ['IUCN'] = {
        ['kode'] = '&nbsp;([[IUCN|IUCN 3.1]])',
        ['EX'] = '[[Vaizdas:Status iucn3.1 EX lt.svg|frameless|link=Apsaugos būklė#Išnykę|alt=]]<br />[[Apsaugos būklė#Išnykę|Išnykę]]',
        ['ex'] = '[[Vaizdas:Status iucn3.1 EX lt.svg|frameless|link=Apsaugos būklė#Išnykę|alt=]]<br />[[Apsaugos būklė#Išnykę|Išnykę]]',
        ['EW'] = '[[Vaizdas:Status iucn3.1 EW lt.svg|frameless|link=Apsaugos būklė#Išnykę laisvėje|alt=]]<br />[[Apsaugos būklė#Išnykę laisvėje|Išnykę laisvėje]]',
        ['ew'] = '[[Vaizdas:Status iucn3.1 EW lt.svg|frameless|link=Apsaugos būklė#Išnykę laisvėje|alt=]]<br />[[Apsaugos būklė#Išnykę laisvėje|Išnykę laisvėje]]',
        ['CR'] = '[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]]',
        ['cr'] = '[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]]',
        ['EN'] = '[[Vaizdas:Status iucn3.1 EN lt.svg|frameless|link=Apsaugos būklė#Nykstantys|alt=]]<br />[[Apsaugos būklė#Nykstantys|Nykstantys]]',
        ['en'] = '[[Vaizdas:Status iucn3.1 EN lt.svg|frameless|link=Apsaugos būklė#Nykstantys|alt=]]<br />[[Apsaugos būklė#Nykstantys|Nykstantys]]',
        ['VU'] = '[[Vaizdas:Status iucn3.1 VU lt.svg|frameless|link=Apsaugos būklė#Pažeidžiami|alt=]]<br />[[Apsaugos būklė#Pažeidžiami|Pažeidžiami]]',
        ['vu'] = '[[Vaizdas:Status iucn3.1 VU lt.svg|frameless|link=Apsaugos būklė#Pažeidžiami|alt=]]<br />[[Apsaugos būklė#Pažeidžiami|Pažeidžiami]]',
        ['NT'] = '[[Vaizdas:Status iucn3.1 NT lt.svg|frameless|link=Apsaugos būklė#Beveik nykstantys|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['nt'] = '[[Vaizdas:Status iucn3.1 NT lt.svg|frameless|link=Apsaugos būklė#Beveik nykstantys|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['LC'] = '[[Vaizdas:Status iucn3.1 LC lt.svg|frameless|link=Apsaugos būklė#Nekeliantys susirūpinimo|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['lc'] = '[[Vaizdas:Status iucn3.1 LC lt.svg|frameless|link=Apsaugos būklė#Nekeliantys susirūpinimo|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['DD'] = '[[Vaizdas:Status iucn3.1 lt.svg|frameless|link=|alt=]]<br/>[[Apsaugos būklė|Trūksta duomenų]]',
        ['dd'] = '[[Vaizdas:Status iucn3.1 lt.svg|frameless|link=|alt=]]<br/>[[Apsaugos būklė|Trūksta duomenų]]',
        ['NE'] = "''Nenustatyta''",
        ['ne'] = "''Nenustatyta''",
        ['NR'] = "''Nežinoma''",
        ['nr'] = "''Nežinoma''",
        ['PE'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę",
        ['pe'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę",
        ['PEW'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę laisvėje",
        ['pew'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę laisvėje",
        ['#default'] = "'''''Blogas statusas'''''"
    },
    ['iucn3.1'] = {
        ['kode'] = '&nbsp;([[IUCN|IUCN 3.1]])',
        ['ex'] = '[[Vaizdas:Status iucn3.1 EX lt.svg|frameless|link=Apsaugos būklė#Išnykę|alt=]]<br />[[Apsaugos būklė#Išnykę|Išnykę]]',
        ['EW'] = '[[Vaizdas:Status iucn3.1 EW lt.svg|frameless|link=Apsaugos būklė#Išnykę laisvėje|alt=]]<br />[[Apsaugos būklė#Išnykę laisvėje|Išnykę laisvėje]]',
        ['ew'] = '[[Vaizdas:Status iucn3.1 EW lt.svg|frameless|link=Apsaugos būklė#Išnykę laisvėje|alt=]]<br />[[Apsaugos būklė#Išnykę laisvėje|Išnykę laisvėje]]',
        ['CR'] = '[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]]',
        ['cr'] = '[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]]',
        ['EN'] = '[[Vaizdas:Status iucn3.1 EN lt.svg|frameless|link=Apsaugos būklė#Nykstantys|alt=]]<br />[[Apsaugos būklė#Nykstantys|Nykstantys]]',
        ['en'] = '[[Vaizdas:Status iucn3.1 EN lt.svg|frameless|link=Apsaugos būklė#Nykstantys|alt=]]<br />[[Apsaugos būklė#Nykstantys|Nykstantys]]',
        ['VU'] = '[[Vaizdas:Status iucn3.1 VU lt.svg|frameless|link=Apsaugos būklė#Pažeidžiami|alt=]]<br />[[Apsaugos būklė#Pažeidžiami|Pažeidžiami]]',
        ['vu'] = '[[Vaizdas:Status iucn3.1 VU lt.svg|frameless|link=Apsaugos būklė#Pažeidžiami|alt=]]<br />[[Apsaugos būklė#Pažeidžiami|Pažeidžiami]]',
        ['NT'] = '[[Vaizdas:Status iucn3.1 NT lt.svg|frameless|link=Apsaugos būklė#Beveik nykstantys|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['nt'] = '[[Vaizdas:Status iucn3.1 NT lt.svg|frameless|link=Apsaugos būklė#Beveik nykstantys|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['LC'] = '[[Vaizdas:Status iucn3.1 LC lt.svg|frameless|link=Apsaugos būklė#Nekeliantys susirūpinimo|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['lc'] = '[[Vaizdas:Status iucn3.1 LC lt.svg|frameless|link=Apsaugos būklė#Nekeliantys susirūpinimo|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['DD'] = '[[Vaizdas:Status iucn3.1 lt.svg|frameless|link=|alt=]]<br/>[[Apsaugos būklė|Trūksta duomenų]]',
        ['dd'] = '[[Vaizdas:Status iucn3.1 lt.svg|frameless|link=|alt=]]<br/>[[Apsaugos būklė|Trūksta duomenų]]',
        ['NE'] = "''Nenustatyta''",
        ['ne'] = "''Nenustatyta''",
        ['NR'] = "''Nežinoma''",
        ['nr'] = "''Nežinoma''",
        ['PE'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę",
        ['pe'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę",
        ['PEW'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę laisvėje",
        ['pew'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę laisvėje",
        ['#default'] = "'''''Blogas statusas'''''"
    },
    ['IUCN3.1'] = {
        ['kode'] = '&nbsp;([[IUCN|IUCN 3.1]])',
        ['ex'] = '[[Vaizdas:Status iucn3.1 EX lt.svg|frameless|link=Apsaugos būklė#Išnykę|alt=]]<br />[[Apsaugos būklė#Išnykę|Išnykę]]',
        ['EW'] = '[[Vaizdas:Status iucn3.1 EW lt.svg|frameless|link=Apsaugos būklė#Išnykę laisvėje|alt=]]<br />[[Apsaugos būklė#Išnykę laisvėje|Išnykę laisvėje]]',
        ['ew'] = '[[Vaizdas:Status iucn3.1 EW lt.svg|frameless|link=Apsaugos būklė#Išnykę laisvėje|alt=]]<br />[[Apsaugos būklė#Išnykę laisvėje|Išnykę laisvėje]]',
        ['CR'] = '[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]]',
        ['cr'] = '[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]]',
        ['EN'] = '[[Vaizdas:Status iucn3.1 EN lt.svg|frameless|link=Apsaugos būklė#Nykstantys|alt=]]<br />[[Apsaugos būklė#Nykstantys|Nykstantys]]',
        ['en'] = '[[Vaizdas:Status iucn3.1 EN lt.svg|frameless|link=Apsaugos būklė#Nykstantys|alt=]]<br />[[Apsaugos būklė#Nykstantys|Nykstantys]]',
        ['VU'] = '[[Vaizdas:Status iucn3.1 VU lt.svg|frameless|link=Apsaugos būklė#Pažeidžiami|alt=]]<br />[[Apsaugos būklė#Pažeidžiami|Pažeidžiami]]',
        ['vu'] = '[[Vaizdas:Status iucn3.1 VU lt.svg|frameless|link=Apsaugos būklė#Pažeidžiami|alt=]]<br />[[Apsaugos būklė#Pažeidžiami|Pažeidžiami]]',
        ['NT'] = '[[Vaizdas:Status iucn3.1 NT lt.svg|frameless|link=Apsaugos būklė#Beveik nykstantys|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['nt'] = '[[Vaizdas:Status iucn3.1 NT lt.svg|frameless|link=Apsaugos būklė#Beveik nykstantys|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['LC'] = '[[Vaizdas:Status iucn3.1 LC lt.svg|frameless|link=Apsaugos būklė#Nekeliantys susirūpinimo|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['lc'] = '[[Vaizdas:Status iucn3.1 LC lt.svg|frameless|link=Apsaugos būklė#Nekeliantys susirūpinimo|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['DD'] = '[[Vaizdas:Status iucn3.1 lt.svg|frameless|link=|alt=]]<br/>[[Apsaugos būklė|Trūksta duomenų]]',
        ['dd'] = '[[Vaizdas:Status iucn3.1 lt.svg|frameless|link=|alt=]]<br/>[[Apsaugos būklė|Trūksta duomenų]]',
        ['NE'] = "''Nenustatyta''",
        ['ne'] = "''Nenustatyta''",
        ['NR'] = "''Nežinoma''",
        ['nr'] = "''Nežinoma''",
        ['PE'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę",
        ['pe'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę",
        ['PEW'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę laisvėje",
        ['pew'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę laisvėje",
        ['#default'] = "'''''Blogas statusas'''''"
    },

    ['#default'] = {
        ['kode'] = '&nbsp;([[IUCN|IUCN 3.1]])',
        ['EX'] = '[[Vaizdas:Status iucn3.1 EX lt.svg|frameless|link=Apsaugos būklė#Išnykę|alt=]]<br />[[Apsaugos būklė#Išnykę|Išnykę]]',
        ['ex'] = '[[Vaizdas:Status iucn3.1 EX lt.svg|frameless|link=Apsaugos būklė#Išnykę|alt=]]<br />[[Apsaugos būklė#Išnykę|Išnykę]]',
        ['EW'] = '[[Vaizdas:Status iucn3.1 EW lt.svg|frameless|link=Apsaugos būklė#Išnykę laisvėje|alt=]]<br />[[Apsaugos būklė#Išnykę laisvėje|Išnykę laisvėje]]',
        ['ew'] = '[[Vaizdas:Status iucn3.1 EW lt.svg|frameless|link=Apsaugos būklė#Išnykę laisvėje|alt=]]<br />[[Apsaugos būklė#Išnykę laisvėje|Išnykę laisvėje]]',
        ['CR'] = '[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]]',
        ['cr'] = '[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]]',
        ['EN'] = '[[Vaizdas:Status iucn3.1 EN lt.svg|frameless|link=Apsaugos būklė#Nykstantys|alt=]]<br />[[Apsaugos būklė#Nykstantys|Nykstantys]]',
        ['en'] = '[[Vaizdas:Status iucn3.1 EN lt.svg|frameless|link=Apsaugos būklė#Nykstantys|alt=]]<br />[[Apsaugos būklė#Nykstantys|Nykstantys]]',
        ['VU'] = '[[Vaizdas:Status iucn3.1 VU lt.svg|frameless|link=Apsaugos būklė#Pažeidžiami|alt=]]<br />[[Apsaugos būklė#Pažeidžiami|Pažeidžiami]]',
        ['vu'] = '[[Vaizdas:Status iucn3.1 VU lt.svg|frameless|link=Apsaugos būklė#Pažeidžiami|alt=]]<br />[[Apsaugos būklė#Pažeidžiami|Pažeidžiami]]',
        ['NT'] = '[[Vaizdas:Status iucn3.1 NT lt.svg|frameless|link=Apsaugos būklė#Beveik nykstantys|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['nt'] = '[[Vaizdas:Status iucn3.1 NT lt.svg|frameless|link=Apsaugos būklė#Beveik nykstantys|alt=]]<br />[[Apsaugos būklė#Beveik nykstantys|Beveik nykstantys]]',
        ['LC'] = '[[Vaizdas:Status iucn3.1 LC lt.svg|frameless|link=Apsaugos būklė#Nekeliantys susirūpinimo|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['lc'] = '[[Vaizdas:Status iucn3.1 LC lt.svg|frameless|link=Apsaugos būklė#Nekeliantys susirūpinimo|alt=]]<br />[[Apsaugos būklė#Nekeliantys susirūpinimo|Nekeliantys susirūpinimo]]',
        ['DD'] = '[[Vaizdas:Status iucn3.1 lt.svg|frameless|link=|alt=]]<br/>[[Apsaugos būklė|Trūksta duomenų]]',
        ['dd'] = '[[Vaizdas:Status iucn3.1 lt.svg|frameless|link=|alt=]]<br/>[[Apsaugos būklė|Trūksta duomenų]]',
        ['NE'] = "''Nenustatyta''",
        ['ne'] = "''Nenustatyta''",
        ['NR'] = "''Nežinoma''",
        ['nr'] = "''Nežinoma''",
        ['PE'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę",
        ['pe'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę",
        ['PEW'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę laisvėje",
        ['pew'] = "[[Vaizdas:Status iucn3.1 CR lt.svg|frameless|link=Apsaugos būklė#Grėsmingai nykstantys|alt=]]<br />[[Apsaugos būklė#Grėsmingai nykstantys|Grėsmingai nykstantys]], tikėtinai išnykę laisvėje",
        ['#default'] = "'''''Blogas statusas'''''"
    },
}

return iucn;
