<?php
# This file was automatically generated by the MediaWiki 1.18.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;
#$wgRCMaxAge=40000;

$wgSitename      = "Enciklopedija Lietuvai ir Pasauliui";
$wgMetaNamespace = "Enciklopedija";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/w";
$wgScriptExtension  = ".php";
$wgArticlePath = '/wiki/$1';
$wgUsePathInfo = true;

## The protocol and server name to use in fully-qualified URLs
$wgServer           = "http://lietuvai.lt";

## The relative URL path to the skins directory
$wgStylePath        = "$wgScriptPath/skins";

## The relative URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo             = "http://lietuvai.lt/w/images/b/bc/Wiki.png";

## UPO means: this is also a user preference option

$wgEnableEmail      = true;
$wgEnableUserEmail  = true; # UPO

$wgEmergencyContact = "vpovilaitis@arklys";
$wgPasswordSender   = "vpovilaitis@arklys";

$wgEnotifUserTalk      = true; # UPO
$wgEnotifWatchlist     = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "localhost";
$wgDBname           = "enciklopedija";
$wgDBuser           = "vartotojas";
$wgDBpassword       = "AbC123";
$wgDBadminuser          = "vartotojas";
$wgDBadminpassword      = "AbC123";

# MySQL specific settings
$wgDBprefix         = "enc";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_ANYTHING;
#$wgMainCacheType = CACHE_NONE;
#$wgMainCacheType    = CACHE_MEMCACHED;
#$wgMemCachedServers = array( '127.0.0.1:11211' );

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads  = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";
$wgUseImageResize = true;
$wgAllowTitlesInSVG = true;
$wgSVGConverter = 'ImageMagick';
$wgThumbnailEpoch='20120502000000';
$wgMaxShellMemory = 204800;

# InstantCommons allows wiki to use images from http://commons.wikimedia.org
$wgUseInstantCommons  = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";
$defaultDateFormat = 'ymd';

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
#$wgHashedUploadDirectory = false;

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
$wgCacheDirectory = "$IP/cache";
$wgUseFileCache = true; /* default: false */
$wgFileCacheDirectory = "$IP/cache";
$wgShowIPinHeader = false;
$wgUseGzip= true;
 
# Site language code, should be one of the list in ./languages/Names.php
$wgLanguageCode = "lt";

$wgSecretKey = "ec94301f2dcda4de6d81504923463ac89c04eeb6a26aedfd3b33820305f55975";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "ee8acb1a77fd0360";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook', 'vector':
$wgDefaultSkin = "vector";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl  = "http://creativecommons.org/licenses/by-sa/3.0/";
$wgRightsText = "Creative Commons Attribution Share Alike";
$wgRightsIcon = "{$wgStylePath}/common/images/cc-by-sa.png";
# $wgRightsCode = ""; # Not yet used

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

# Query string length limit for ResourceLoader. You should only set this if
# your web server has a query string length limit (then set it to that limit),
# or if you have suhosin.get.max_value_length set in php.ini (then set it to
# that value)
$wgResourceLoaderMaxQueryLength = -1;

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = false;
#$wgGroupPermissions['*']['edit'] = false;

# Enabled Extensions. Most extensions are enabled by including the base extension file here
# but check specific extension documentation for more details
# The following extensions were automatically enabled:
require_once( "$IP/extensions/ConfirmEdit/ConfirmEdit.php" );
require_once( "$IP/extensions/Gadgets/Gadgets.php" );
require_once( "$IP/extensions/ParserFunctions/ParserFunctions.php" );
require_once( "$IP/extensions/Vector/Vector.php" );
require_once( "$IP/extensions/Renameuser/Renameuser.php" );
require_once( "$IP/extensions/WikiEditor/WikiEditor.php" );
require_once( "$IP/extensions/Nuke/Nuke.php" );

# End of automatically generated settings.
# Add more configuration options below.

# Editor toolbar WikiEditor
$wgDefaultUserOptions['usebetatoolbar'] = 1;
$wgDefaultUserOptions['usebetatoolbar-cgd'] = 1;
$wgDefaultUserOptions['wikieditor-preview'] = 1;

# Extension:Vector
$wgDefaultUserOptions['useeditwarning'] = 1;
$wgVectorFeatures['editwarning']['user'] = true;
$wgVectorFeatures['collapsibletabs']['user'] = true;
$wgVectorFeatures['collapsiblenav']['user'] = true;
$wgVectorFeatures['expandablesearch']['global'] = true;

require_once("{$IP}/extensions/Slideshow/slideshow.php");
require_once("$IP/extensions/intersection/DynamicPageList.php");
require_once( "$IP/extensions/DPLforum/DPLforum.php" );

require_once("$IP/extensions/InputBox/InputBox.php");
$wgUseAjax = true;

require_once("$IP/extensions/CategoryTree/CategoryTree.php");
$wgUseAjax = true;

require_once("$IP/extensions/CharInsert/CharInsert.php");
require_once("$IP/extensions/Cite/Cite.php");
require_once("$IP/extensions/ImageMap/ImageMap.php");
require_once("$IP/extensions/LiquidThreads/LiquidThreads.php");

require_once( "$IP/extensions/MiniMp3/MiniMp3.php");
require_once("$IP/extensions/PdfHandler/PdfHandler.php");
$wgPdfProcessor = 'gs';
$wgPdfPostProcessor = $wgImageMagickConvertCommand;
$wgPdfInfo = 'pdfinfo';
$wgFileExtensions = array( 'png', 'gif', 'jpg', 'jpeg', 'mp3' , 'svg', 'pdf');

require_once ("$IP/extensions/StringFunctions/StringFunctions.php");
require_once("$IP/extensions/ApiSandbox/ApiSandbox.php");

require_once("$IP/extensions/TitleKey/TitleKey.php");
$wgEnableMWSuggest = true;

require_once( "$IP/extensions/semantic-bundle/SemanticBundleSettings.php" );
require_once( "$IP/extensions/semantic-bundle/SemanticBundle.php" );
$srfgFormats[] = 'googlebar';
$srfgFormats[] = 'googlepie';

# Extension:ConfirmAccount
require_once("$IP/extensions/ConfirmAccount/ConfirmAccount.php");
$wgMakeUserPageFromBio = true;
$wgAutoWelcomeNewUsers = true;
$wgUseRealNamesOnly = false;
$wgAccountRequestMinWords = 25;
$wgConfirmAccountContact = true;

require_once("$IP/extensions/SemanticFormsSelect/SemanticFormsSelect.php");

require_once("$IP/extensions/Poem/Poem.php");
require_once("$IP/extensions/wikihiero/wikihiero.php");

require_once("{$IP}/extensions/Interwiki/Interwiki.php");
$wgGroupPermissions['*']['interwiki'] = false;
$wgGroupPermissions['bureaucrat']['interwiki'] = true;
$wgEnableScaryTranscluding = true;
$wgInterwikiMagic = true;
$wgHideInterlanguageLinks = false;

require_once( "$IP/extensions/Configure/Configure.php" );
efConfigureSetup();
#$wgConfigureEditableSettings = array();
$wgConfigureDatabase = false;

$wgFlaggedRevsStatsAge = false;
require_once("$IP/extensions/FlaggedRevs/FlaggedRevs.php");
#$wgGroupPermissions['sysop']['review'] = true;
$wgGroupPermissions['bot']['autoreview'] = false;
$wgGroupPermissions['autoreview']['autoreview'] = true;
$wgFlaggedRevsTags = array(
	'accuracy' => array( 'levels' => 4, 'quality' => 2, 'pristine' => 4 ),
	'depth'    => array( 'levels' => 4, 'quality' => 1, 'pristine' => 4 ),
	'style'    => array( 'levels' => 4, 'quality' => 1, 'pristine' => 4 ),
);
$wgFlaggedRevsTagsRestrictions = array(
	'accuracy' => array( 'bureaucrat' => 4, 'validate' => 3, 'review' => 1, 'autoreview' => 1 ),
	'depth'	   => array( 'bureaucrat' => 4, 'validate' => 3, 'review' => 2, 'autoreview' => 1 ),
	'style'	   => array( 'bureaucrat' => 4, 'validate' => 3, 'review' => 2, 'autoreview' => 1 ),
);

$wgFlaggedRevsAutopromote['edits'] = 500;
$wgFlaggedRevsAutopromote['totalContentEdits'] = 450; # $wgContentNamespaces edits
$wgFlaggedRevsAutopromote['uniqueContentPages'] = 200; # $wgContentNamespaces unique pages edited
$wgFlaggedRevsAutopromote['email'] = true; # user must be emailconfirmed?
$wgFlaggedRevsAutopromote['userpageBytes'] = 5000; # if userpage is needed, what is the min size?
$wgSimpleFlaggedRevsUI = true;

require_once("$IP/extensions/uniwiki/Authors/Authors.php");

$wgNamespacesWithSubpages[4] = true;
$wgExtraNamespaces[5] = "Enciklopedijos_aptarimas";
$wgNamespaceAliases['File'] = 6;
$wgNamespaceAliases['File talk'] = 7;
$wgNamespacesWithSubpages[0] = true;
$wgNamespacesWithSubpages[10] = true;
$wgNamespacesWithSubpages[12] = true;
$wgNamespaceProtection[6]      = array( 'only-user-edit' );
$wgNamespaceProtection[10]      = array( 'only-user-edit' );
$wgNamespaceProtection[14]      = array( 'only-user-edit' );
$wgNamespaceProtection[102]      = array( 'only-user-edit' );
$wgNamespaceProtection[106]      = array( 'only-user-edit' );
$wgNamespaceProtection[108]      = array( 'only-user-edit' );
$wgNamespaceProtection[170]      = array( 'only-user-edit' );
$wgGroupPermissions['user']['only-user-edit'] = true;

#define("SRITIS", 800);
#define("SRITIS_TALK", 801);
$wgShowAuthorsNamespaces = array (NS_MAIN, NS_IMAGE, 800); # (array) Controls which namespaces this extension affects
$wgFlaggedRevsNamespaces[] = 800;

$wgExtraNamespaces[800] = "Sritis";
$wgExtraNamespaces[801] = "Srities_aptarimas";
$wgNamespaceAliases['Portal'] = 800;
$wgNamespaceAliases['Portal_talk'] = 801;
$wgNamespaceAliases['Sritis'] = 800;
$wgNamespaceAliases['Srities_aptarimas'] = 801;
$wgNamespacesWithSubpages[800] = true;
$wgNamespacesWithSubpages[801] = true;
$wgNamespacesToBeSearchedDefault[800] = true;
$smwgNamespacesWithSemanticLinks[800] = true;

$wgExtraNamespaces[110] = "Indeksas";
$wgExtraNamespaces[111] = "Indekso_aptarimas";
$wgNamespaceAliases['Index'] = 110;
$wgNamespaceAliases['Index_talk'] = 111;
$wgNamespaceAliases['Indeksas'] = 110;
$wgNamespaceAliases['Indekso_aptarimas'] = 111;
$wgNamespacesWithSubpages[110] = true;
$wgNamespacesWithSubpages[111] = true;
$wgNamespacesToBeSearchedDefault[110] = true;
$smwgNamespacesWithSemanticLinks[110] = true;
$wgFlaggedRevsNamespaces[] = 110;
$wgShowAuthorsNamespaces[] = 110;

$wgExtraNamespaces[112] = "Puslapis";
$wgExtraNamespaces[113] = "Puslapio_aptarimas";
$wgNamespaceAliases['Page'] = 112;
$wgNamespaceAliases['Page_talk'] = 113;
$wgNamespaceAliases['Puslapis'] = 112;
$wgNamespaceAliases['Puslapio_aptarimas'] = 113;
$wgNamespacesWithSubpages[112] = true;
$wgNamespacesWithSubpages[113] = true;
$wgNamespacesToBeSearchedDefault[112] = true;
$smwgNamespacesWithSemanticLinks[112] = true;
$wgFlaggedRevsNamespaces[] = 112;
$wgShowAuthorsNamespaces[] = 112;

$wgExtraNamespaces[90] = "Žinutė";
$wgExtraNamespaces[91] = "Žinutės_aptarimas";
$wgNamespaceAliases['Thread'] = 90;
$wgNamespaceAliases['Thread_talk'] = 91;
$wgNamespacesWithSubpages[91] = true;

$wgExtraNamespaces[92] = "Apibendrinimas";
$wgExtraNamespaces[93] = "Apibendrinimo_aptarimas";
$wgNamespaceAliases['Summary'] = 92;
$wgNamespaceAliases['Summary_talk'] = 93;
$wgNamespacesWithSubpages[93] = true;

$wgExtraNamespaces[102] = "Savybė";
$wgExtraNamespaces[103] = "Savybės_aptarimas";
$wgNamespaceAliases['Property'] = 102;
$wgNamespaceAliases['Property_talk'] = 103;

$wgExtraNamespaces[106] = "Forma";
$wgExtraNamespaces[107] = "Formos_aptarimas";
$wgNamespaceAliases['Form'] = 106;
$wgNamespaceAliases['Form talk'] = 107;

$wgExtraNamespaces[108] = "Koncepcija";
$wgExtraNamespaces[109] = "Koncepcijos_aptarimas";
$wgNamespaceAliases['Concept'] = 108;
$wgNamespaceAliases['Concept_talk'] = 109;
$wgNamespacesWithSubpages[109] = true;

$wgExtraNamespaces[170] = "Filtras";
$wgExtraNamespaces[171] = "Filtro_aptarimas";
$wgNamespaceAliases['Filter'] = 170;
$wgNamespaceAliases['Filter_talk'] = 171;

$wgExtraNamespaces[274] = "Intarpas";
$wgExtraNamespaces[275] = "Intarpo_aptarimas";
$wgNamespaceAliases['Widget'] = 274;
$wgNamespaceAliases['Widget_talk'] = 275;

$wgExtraNamespaces[420] = "Sluoksnis";
$wgExtraNamespaces[421] = "Sluoksnio_aptarimas";
$wgNamespaceAliases['Layer'] = 420;
$wgNamespaceAliases['Layer_talk'] = 421;
$wgNamespacesWithSubpages[421] = true;

$wgContentNamespaces = array (0, 102, 110, 112, 800);

#$wgGroupPermissions['*']['edit'] = true;
#$wgGroupPermissions['*']['createpage'] = false;

$wgShowExceptionDetails = true;

#require_once("$IP/extensions/SpecialForm.php")
$wgFormTablePrefix = "form_";
$wgAutoCreateFormTable = true;
$wgFormSender = $wgPasswordSender;

$edgDBServer['form'] = "127.0.0.1";
$edgDBServerType['form'] = "mysql"; 
$edgDBName['form'] = "lituacom_encikW";
$edgDBUser['form'] = "lituacom_vitas";
$edgDBPass['form'] = "povas15101";
#$edgDBFlags['form'] = DBO_NOBUFFER & DBO_TRX;
$edgDBTablePrefix['form'] = "form_";

$wgGroupPermissions['showeform']['showform'] = true;

require_once("$IP/extensions/timeline/EasyTimeline.php"); // Add EasyTimeline extension
putenv("GDFONTPATH=/usr/share/fonts/TTF");
#$wgTimelineSettings->fileBackend = "/var/www/htdocs/images/timeline";
#$wgTimelineSettings->ploticusCommand = "/usr/bin/ploticus";
$wgTimelineSettings->ploticusCommand = "/usr/local/bin/pl";
#$wgTimelineSettings->perlCommand = "/usr/bin/perl";

require_once( "$IP/extensions/OpenSearchXml/OpenSearchXml.php" );
require_once("$IP/extensions/TitleKey/TitleKey.php");

require( "$IP/extensions/DynamicSidebar/DynamicSidebar.php" );
// Enable debugging
#$wgDebugLogGroups["dynamic-sidebar"] = "/tmp/sidebar-debug.txt";
 
// Allow users to create their own custom sidebars under User:<username>/Sidebar
// Default: true
$wgDynamicSidebarUseUserpages = true;
 
// Allow group sidebars under MediaWiki:Sidebar/Group:<group>
// Default: true
$wgDynamicSidebarUseGroups = true;
 
// Allow category based sidebars under MediaWiki:Sidebar/Category:<category>
// Default: true
$wgDynamicSidebarUseCategories = true;

# Math modulio konfiguracija, Audrius Meskauskas
$wgTexvc = '/var/www/enciklopedija/w/extensions/Math/math/texvc';
require_once("$IP/extensions/Math/Math.php");

require_once( "$IP/extensions/ProofreadPage/ProofreadPage.php" );

#require_once($IP.'/extensions/ManualSitemap/ManualSitemap.php');
# Notify all web sites you want about the update of sitemap
$sitemap=urlencode('http://lietuvai.lt/wiki/sitemap.xml');
$ManualSitemap_Notify=array();
$ManualSitemap_Notify[] = 'http://www.google.com/webmasters/sitemaps/ping?sitemap='.$sitemap;
$ManualSitemap_Notify[] = 'http://search.yahooapis.com/SiteExplorerService/V1/ping?sitemap='.$sitemap;
$ManualSitemap_Notify[] = 'http://webmaster.live.com/ping.aspx?sitemap='.$sitemap;
$ManualSitemap_Notify[] = 'http://api.moreover.com/ping?u='.$sitemap;
$ManualSitemap_Notify[] = 'http://submissions.ask.com/ping?sitemap='.$sitemap;

# Exclude pages from sitemap (value "1" means "exclude"):

#Please refer to
#http://www.mediawiki.org/wiki/Help:Namespaces
#for more detailed explanation
$ManualSitemap_Exclude=array(
        NS_MAIN =>           '0',       NS_TALK =>           '1',
        NS_USER =>           '1',       NS_USER_TALK =>      '1',
        NS_PROJECT =>        '0',       NS_PROJECT_TALK =>   '1',
        NS_IMAGE =>          '0',       NS_IMAGE_TALK =>     '1',
        NS_MEDIAWIKI =>      '1',       NS_MEDIAWIKI_TALK => '1',
        NS_TEMPLATE =>       '1',       NS_TEMPLATE_TALK =>  '1',
        NS_HELP =>           '1',       NS_HELP_TALK =>      '1',
        NS_CATEGORY =>       '1',       NS_CATEGORY_TALK =>  '1',
        800 => '0', 801 => '1',
        110 => '0', 111 => '1',
        112 => '0', 113 => '1',
        90 => '1', 91 => '1',
        92 => '1', 93 => '1',
        102 => '0', 103 => '1',
        106 => '0', 107 => '1',
        108 => '1', 109 => '1',
        170 => '1', 171 => '1',
        274 => '1', 275 => '1',
        420 => '1', 421 => '1',
);
$wgSitemapNamespaces=array(
        NS_MAIN, NS_PROJECT, NS_IMAGE,  800, 110 , 112 , 102, 106 
);

$ManualSitemap_ServerBase = "http://lietuvai.lt";
#With that all sitemap entries get this as their base url. If not set $wgServer is used

require_once( "$IP/extensions/ReplaceSet/ReplaceSet.php" );

require_once("/home/enciklopedija/w/extensions/ABC/ABC.php");
$abcPath = "/home/enciklopedija/w/phase3/abc";
$abcURL = "/w/phase3/abc";
$abcm2ps = "/usr/local/bin/abcm2ps";
$abcps2pdf = "/usr/local/bin/ps2pdf14";
